application:
  name: jj-strapi
  project: j-j
  publicly_accessible: true
databases:
  - type: postgresql # qovery will create a managed PostgreSQL database
    version: 12
    name: psql
routers:
  - name: main
    routes:
      - application_name: jj-strapi
        paths:
          - /*
